# Database Configuration - This should be like this and get inject at CI/CD pipeline.
spring.datasource.url=jdbc:postgresql://localhost:5432/project1
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HCaptcha
hcaptcha.secret=

# JWT Configuration - Create test secret at https://jwtsecret.com/generate
jwt.secret=990652de6da59d42ecf659c9043dad36fd2fcd6727c9987bc879a19158b52cd93062edf509bd1cd610c58da96e9e4d16dba14783b482a3a24eea353ec6c45ec674d1444abfed4d658d3420a4ca5d1f7b55eabda586cebc658061963dda2587e120d8d18467e16b51fcbf30d916d816a5c81ef21cc068868eb5600ea8bd7a4c67009b052fe1f707889332b234ce2d847eb8e6d0dd3cbc8eb1bcd1dea3b1efe4153aed766ac41d44d2c57997fb81f8106b2f86496196aaddce2ffa76219bb21235c71f83a27312b841e380ed823e364939f34cf1a4789312326638bc21751febc176e3e40dc36aa3f55b1f03e905b5d4d480f1b69cabb6b67eb293f473c4bf7516
jwt.expiration=86400

# For the use of Argon2 encoder.
argon2.saltLength=16
argon2.hashLength=32
argon2.parallelism=1
argon2.memory=65536
argon2.iterations=4

# File Path
app.resource.path=Z:/Revature/Project1/Resource/
file.resource.url="http://localhost:8080/files/"

# Cross Origin
cors.allowed-origins=http://localhost:5173, https://devature.dev, https://www.devature.dev, https://master.d26tmtgdit1rgx.amplifyapp.com