name: Unit Test Action Front

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd project2-front
          npm install

      - name: Run unit tests
        run: |
          cd project2-front
          npm build